app:
  version: 0.0.1
server:
  port: 8888
spring:
  datasource:
    url: jdbc:postgresql:jpaps
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
